import fs from 'fs';
import path from 'path';
import nodeResolve from '@rollup/plugin-node-resolve';
import copy from 'rollup-plugin-copy';
import terser from '@rollup/plugin-terser';
import styles from 'rollup-plugin-styles';
import json from '@rollup/plugin-json';
import image from '@rollup/plugin-image';
import replace from '@rollup/plugin-replace';
import url from '@rollup/plugin-url';

const isProduction = process.env.BUILD === 'production';

writeIcons();
writePopulation();

export default (async () => ({
	input: './src/client/js/application.js',
	output: {
		file: './build/client/js/application.js',
		format: 'esm'
	},
	plugins: [
		replace({
			preventAssignment: true,
			__isProduction__: isProduction,
		}),
		styles({
			url: false,
			mode: [
				'inject',
				(varname) => `import { styleInject } from 'harmony-ui';styleInject(${varname});`
			],
		}),
		json({
			compact: true,
		}),
		url({
			include: ['**/*.gz'],
			limit: 1000000,
		}),
		image(),
		nodeResolve({
		}),
		isProduction ? terser() : null,
		copy({
			copyOnce: true,
			targets: [
				{src: 'src/client/index.html', dest: 'build/client/'},
			]
		}),
	],
}))();

function writeIcons() {
	let iconsPath = './src/client/json/datas/classicons.json';
	let input = fs.readFileSync(iconsPath);
	const classIcons = JSON.parse(input);

	let fileContent = '// This file was generated by rollup\n';
	// First write the imports
	for (const classIcon of classIcons) {
		fileContent += `import ${classIcon} from '../../../img/classicons/leaderboard_class_${classIcon}.png';\n`;
	}

	fileContent += '\nexport const CLASS_ICONS = {\n';
	for (const classIcon of classIcons) {
		fileContent += `	${classIcon}: ${classIcon},\n`;
	}
	fileContent += '}\n';

	fs.writeFile(`./src/client/js/view/elements/classicons.js`, Buffer.from(fileContent), async (err) => {if (err) throw err});
}


function writePopulation() {
	let populationPath = './population/';

	const files = fs.readdirSync(populationPath);
	const gzFiles = files.filter(el => path.extname(el) === '.gz')

	let fileContent = '// This file was generated by rollup\n';
	for (const file of gzFiles) {
		fileContent += `import ${file.replace(/\.pop.gz$/, '')} from '../../../../population/${file}';\n`;
	}

	fileContent += '\nexport const COMPRESSED_OFFICIAL_POPULATION = {\n';
	for (const file of gzFiles) {
		fileContent += `	${file.replace(/\.pop.gz$/, '')}: ${file.replace(/\.pop.gz$/, '')},\n`;
	}
	fileContent += '}\n';


	fs.writeFile(`./src/client/js/datas/compressedofficialpopulation.js`, Buffer.from(fileContent), async (err) => {if (err) throw err});
}
