// This file was generated by rollup
import demo from '../../../img/classicons/leaderboard_class_demo.png';
import demo_bomber from '../../../img/classicons/leaderboard_class_demo_bomber.png';
import demo_burst from '../../../img/classicons/leaderboard_class_demo_burst.png';
import demoknight from '../../../img/classicons/leaderboard_class_demoknight.png';
import demoknight_samurai from '../../../img/classicons/leaderboard_class_demoknight_samurai.png';
import engineer from '../../../img/classicons/leaderboard_class_engineer.png';
import heavy from '../../../img/classicons/leaderboard_class_heavy.png';
import heavy_champ from '../../../img/classicons/leaderboard_class_heavy_champ.png';
import heavy_chief from '../../../img/classicons/leaderboard_class_heavy_chief.png';
import heavy_deflector from '../../../img/classicons/leaderboard_class_heavy_deflector.png';
import heavy_deflector_healonkill from '../../../img/classicons/leaderboard_class_heavy_deflector_healonkill.png';
import heavy_deflector_push from '../../../img/classicons/leaderboard_class_heavy_deflector_push.png';
import heavy_gru from '../../../img/classicons/leaderboard_class_heavy_gru.png';
import heavy_heater from '../../../img/classicons/leaderboard_class_heavy_heater.png';
import heavy_mittens from '../../../img/classicons/leaderboard_class_heavy_mittens.png';
import heavy_shotgun from '../../../img/classicons/leaderboard_class_heavy_shotgun.png';
import heavy_steelfist from '../../../img/classicons/leaderboard_class_heavy_steelfist.png';
import heavy_urgent from '../../../img/classicons/leaderboard_class_heavy_urgent.png';
import medic from '../../../img/classicons/leaderboard_class_medic.png';
import medic_uber from '../../../img/classicons/leaderboard_class_medic_uber.png';
import pyro from '../../../img/classicons/leaderboard_class_pyro.png';
import pyro_flare from '../../../img/classicons/leaderboard_class_pyro_flare.png';
import scout from '../../../img/classicons/leaderboard_class_scout.png';
import scout_bat from '../../../img/classicons/leaderboard_class_scout_bat.png';
import scout_bonk from '../../../img/classicons/leaderboard_class_scout_bonk.png';
import scout_fan from '../../../img/classicons/leaderboard_class_scout_fan.png';
import scout_giant_fast from '../../../img/classicons/leaderboard_class_scout_giant_fast.png';
import scout_jumping from '../../../img/classicons/leaderboard_class_scout_jumping.png';
import scout_shortstop from '../../../img/classicons/leaderboard_class_scout_shortstop.png';
import scout_stun from '../../../img/classicons/leaderboard_class_scout_stun.png';
import scout_stun_armored from '../../../img/classicons/leaderboard_class_scout_stun_armored.png';
import sentry_buster from '../../../img/classicons/leaderboard_class_sentry_buster.png';
import sniper from '../../../img/classicons/leaderboard_class_sniper.png';
import sniper_bow from '../../../img/classicons/leaderboard_class_sniper_bow.png';
import sniper_bow_multi from '../../../img/classicons/leaderboard_class_sniper_bow_multi.png';
import sniper_jarate from '../../../img/classicons/leaderboard_class_sniper_jarate.png';
import sniper_sydneysleeper from '../../../img/classicons/leaderboard_class_sniper_sydneysleeper.png';
import soldier from '../../../img/classicons/leaderboard_class_soldier.png';
import soldier_backup from '../../../img/classicons/leaderboard_class_soldier_backup.png';
import soldier_barrage from '../../../img/classicons/leaderboard_class_soldier_barrage.png';
import soldier_blackbox from '../../../img/classicons/leaderboard_class_soldier_blackbox.png';
import soldier_buff from '../../../img/classicons/leaderboard_class_soldier_buff.png';
import soldier_burstfire from '../../../img/classicons/leaderboard_class_soldier_burstfire.png';
import soldier_conch from '../../../img/classicons/leaderboard_class_soldier_conch.png';
import soldier_crit from '../../../img/classicons/leaderboard_class_soldier_crit.png';
import soldier_libertylauncher from '../../../img/classicons/leaderboard_class_soldier_libertylauncher.png';
import soldier_major_crits from '../../../img/classicons/leaderboard_class_soldier_major_crits.png';
import soldier_sergeant_crits from '../../../img/classicons/leaderboard_class_soldier_sergeant_crits.png';
import soldier_spammer from '../../../img/classicons/leaderboard_class_soldier_spammer.png';
import special_blimp from '../../../img/classicons/leaderboard_class_special_blimp.png';
import spy from '../../../img/classicons/leaderboard_class_spy.png';
import tank from '../../../img/classicons/leaderboard_class_tank.png';
import teleporter from '../../../img/classicons/leaderboard_class_teleporter.png';

export const CLASS_ICONS = {
	demo: demo,
	demo_bomber: demo_bomber,
	demo_burst: demo_burst,
	demoknight: demoknight,
	demoknight_samurai: demoknight_samurai,
	engineer: engineer,
	heavy: heavy,
	heavy_champ: heavy_champ,
	heavy_chief: heavy_chief,
	heavy_deflector: heavy_deflector,
	heavy_deflector_healonkill: heavy_deflector_healonkill,
	heavy_deflector_push: heavy_deflector_push,
	heavy_gru: heavy_gru,
	heavy_heater: heavy_heater,
	heavy_mittens: heavy_mittens,
	heavy_shotgun: heavy_shotgun,
	heavy_steelfist: heavy_steelfist,
	heavy_urgent: heavy_urgent,
	medic: medic,
	medic_uber: medic_uber,
	pyro: pyro,
	pyro_flare: pyro_flare,
	scout: scout,
	scout_bat: scout_bat,
	scout_bonk: scout_bonk,
	scout_fan: scout_fan,
	scout_giant_fast: scout_giant_fast,
	scout_jumping: scout_jumping,
	scout_shortstop: scout_shortstop,
	scout_stun: scout_stun,
	scout_stun_armored: scout_stun_armored,
	sentry_buster: sentry_buster,
	sniper: sniper,
	sniper_bow: sniper_bow,
	sniper_bow_multi: sniper_bow_multi,
	sniper_jarate: sniper_jarate,
	sniper_sydneysleeper: sniper_sydneysleeper,
	soldier: soldier,
	soldier_backup: soldier_backup,
	soldier_barrage: soldier_barrage,
	soldier_blackbox: soldier_blackbox,
	soldier_buff: soldier_buff,
	soldier_burstfire: soldier_burstfire,
	soldier_conch: soldier_conch,
	soldier_crit: soldier_crit,
	soldier_libertylauncher: soldier_libertylauncher,
	soldier_major_crits: soldier_major_crits,
	soldier_sergeant_crits: soldier_sergeant_crits,
	soldier_spammer: soldier_spammer,
	special_blimp: special_blimp,
	spy: spy,
	tank: tank,
	teleporter: teleporter,
}
