const line1 = '// This file has been generated by https://mvm.tf';
const line2 = '// Copy this file in your tf/scripts/population folder';

export const INSERT_BEFORE = `${line1}\n${line2}\n`;
export const INSERT_AFTER = `${line1}\n`;
