// This file was generated by rollup
import mvm_bigrock from '../../../../population/mvm_bigrock.pop.gz';
import mvm_bigrock_advanced1 from '../../../../population/mvm_bigrock_advanced1.pop.gz';
import mvm_bigrock_advanced2 from '../../../../population/mvm_bigrock_advanced2.pop.gz';
import mvm_coaltown from '../../../../population/mvm_coaltown.pop.gz';
import mvm_coaltown_advanced from '../../../../population/mvm_coaltown_advanced.pop.gz';
import mvm_coaltown_advanced2 from '../../../../population/mvm_coaltown_advanced2.pop.gz';
import mvm_coaltown_expert1 from '../../../../population/mvm_coaltown_expert1.pop.gz';
import mvm_coaltown_intermediate from '../../../../population/mvm_coaltown_intermediate.pop.gz';
import mvm_coaltown_intermediate2 from '../../../../population/mvm_coaltown_intermediate2.pop.gz';
import mvm_decoy from '../../../../population/mvm_decoy.pop.gz';
import mvm_decoy_advanced from '../../../../population/mvm_decoy_advanced.pop.gz';
import mvm_decoy_advanced2 from '../../../../population/mvm_decoy_advanced2.pop.gz';
import mvm_decoy_advanced3 from '../../../../population/mvm_decoy_advanced3.pop.gz';
import mvm_decoy_expert1 from '../../../../population/mvm_decoy_expert1.pop.gz';
import mvm_decoy_intermediate from '../../../../population/mvm_decoy_intermediate.pop.gz';
import mvm_decoy_intermediate2 from '../../../../population/mvm_decoy_intermediate2.pop.gz';
import mvm_ghost_town from '../../../../population/mvm_ghost_town.pop.gz';
import mvm_ghost_town_666 from '../../../../population/mvm_ghost_town_666.pop.gz';
import mvm_mannhattan from '../../../../population/mvm_mannhattan.pop.gz';
import mvm_mannhattan_advanced1 from '../../../../population/mvm_mannhattan_advanced1.pop.gz';
import mvm_mannhattan_advanced2 from '../../../../population/mvm_mannhattan_advanced2.pop.gz';
import mvm_mannworks from '../../../../population/mvm_mannworks.pop.gz';
import mvm_mannworks_advanced from '../../../../population/mvm_mannworks_advanced.pop.gz';
import mvm_mannworks_expert1 from '../../../../population/mvm_mannworks_expert1.pop.gz';
import mvm_mannworks_intermediate from '../../../../population/mvm_mannworks_intermediate.pop.gz';
import mvm_mannworks_intermediate2 from '../../../../population/mvm_mannworks_intermediate2.pop.gz';
import mvm_mannworks_ironman from '../../../../population/mvm_mannworks_ironman.pop.gz';
import mvm_rottenburg from '../../../../population/mvm_rottenburg.pop.gz';
import mvm_rottenburg_advanced1 from '../../../../population/mvm_rottenburg_advanced1.pop.gz';
import mvm_rottenburg_advanced2 from '../../../../population/mvm_rottenburg_advanced2.pop.gz';
import robot_gatebot from '../../../../population/robot_gatebot.pop.gz';
import robot_giant from '../../../../population/robot_giant.pop.gz';
import robot_standard from '../../../../population/robot_standard.pop.gz';

export const COMPRESSED_OFFICIAL_POPULATION = {
	mvm_bigrock: mvm_bigrock,
	mvm_bigrock_advanced1: mvm_bigrock_advanced1,
	mvm_bigrock_advanced2: mvm_bigrock_advanced2,
	mvm_coaltown: mvm_coaltown,
	mvm_coaltown_advanced: mvm_coaltown_advanced,
	mvm_coaltown_advanced2: mvm_coaltown_advanced2,
	mvm_coaltown_expert1: mvm_coaltown_expert1,
	mvm_coaltown_intermediate: mvm_coaltown_intermediate,
	mvm_coaltown_intermediate2: mvm_coaltown_intermediate2,
	mvm_decoy: mvm_decoy,
	mvm_decoy_advanced: mvm_decoy_advanced,
	mvm_decoy_advanced2: mvm_decoy_advanced2,
	mvm_decoy_advanced3: mvm_decoy_advanced3,
	mvm_decoy_expert1: mvm_decoy_expert1,
	mvm_decoy_intermediate: mvm_decoy_intermediate,
	mvm_decoy_intermediate2: mvm_decoy_intermediate2,
	mvm_ghost_town: mvm_ghost_town,
	mvm_ghost_town_666: mvm_ghost_town_666,
	mvm_mannhattan: mvm_mannhattan,
	mvm_mannhattan_advanced1: mvm_mannhattan_advanced1,
	mvm_mannhattan_advanced2: mvm_mannhattan_advanced2,
	mvm_mannworks: mvm_mannworks,
	mvm_mannworks_advanced: mvm_mannworks_advanced,
	mvm_mannworks_expert1: mvm_mannworks_expert1,
	mvm_mannworks_intermediate: mvm_mannworks_intermediate,
	mvm_mannworks_intermediate2: mvm_mannworks_intermediate2,
	mvm_mannworks_ironman: mvm_mannworks_ironman,
	mvm_rottenburg: mvm_rottenburg,
	mvm_rottenburg_advanced1: mvm_rottenburg_advanced1,
	mvm_rottenburg_advanced2: mvm_rottenburg_advanced2,
	robot_gatebot: robot_gatebot,
	robot_giant: robot_giant,
	robot_standard: robot_standard,
}
